sudo: required
language: go
services:
- docker
env:
  global:
  - DOCKER_VERSION=1.12.0-0~trusty
  - DOCKER_COMPOSE_VERSION=1.7.0
branches:
  except:
  - /^v\d/
before_install:
- apt-cache madison docker-engine
- sudo apt-get update -q
# - sudo apt-get -o Dpkg::Options::="--force-confnew" install -y --force-yes docker-engine=${DOCKER_VERSION}
- sudo rm /usr/local/bin/docker-compose
- curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname
  -s`-`uname -m` > docker-compose
- chmod +x docker-compose
- sudo mv docker-compose /usr/local/bin
- sudo add-apt-repository ppa:duggan/bats --yes
- sudo apt-get update -qq
- sudo apt-get install -qq bats
- curl -s https://raw.githubusercontent.com/ZZROTDesign/docker-clean/master/docker-clean | sudo tee /usr/local/bin/docker-clean > /dev/null && sudo chmod +x /usr/local/bin/docker-clean
install:
- docker-compose -f docker-compose.travis.yml build
script:
- docker version
- docker-compose version
- bats tests/caddy.bats
notifications:
  email:
    on_success: never
  slack:
    secure: Q9Iaa3DQacVbmEhCiBUj6JxVPHm3CrBHBmIgDolp7A4pe4U4GJytrTXJVRArWfu6HA9FP678Hm+h3Mh1xNiCB28VIpESHqQ4qaYKuPidM7YVLVezGXgL473fjdc3W9yZ/+GyHolqWdncXC4530IvcmLN6gIi8mUm+wYKjnZNHN/DUfBOQ52VtRs+HiriFZVFL3NNHAJJgtSkaNVs7f//KQidMTqFvnmkvnpQnOEjWSYIMJ+f7AxPdXis0wOIADhC0/r6fhHddrjIQ93JaHbji8kpWLSoQH9RAmHBCglE94cINd4nOGoTuAK+eZjGNaxJAWgSilc1mZYWdibv2kRXaMHVf1K801whqXyMLL6f3ikUB6KsEQuYIPgOkKas+gI0YzAlicRc3Tbvk94FNnS3XPM5D1jzX4iluqDPoABZ66JNts/EGuHJ3i2dPuJCfxOVJVoBXbkJiIhNicpfrBiw+W5Od+ZJswGys3TsCV6Ou0WdUKk6WFYTnOb3ND2tAn9R+LiFffNBxd+pymaSGAINH/SsWeAWF9pjjcOiUzJzsNuz5hXk3sE+PKBlnamuxaG0NmefWrLtRW7CvTET+G/+EIoaOw2qJxqeoqytRdm9qjekSkJ5Twc226vue1nLl9XgLRcn/PGCyDG4Z3jNEZ5a+sqL21Qvknum7YTnQQSL7ns=
