version: '2'
  services:
    caddy:
      build: .
      ports:
        - 80:80
        - 443:443
      volumes:
        - ./Caddyfile:/etc/Caddyfile
        - ./public:/var/www/html
        - ./.caddy/root/.caddy
